name: rupgt_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - conda-forge::cookiecutter
  - ca-certificates
  - openssl
  - conda-forge::huggingface_hub
  - certifi
  - jupyterlab
  - conda-forge::transformers
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - conda-forge::accelerate
  - conda-forge::requests=2.27.1
