name: rugpt_dev
channels:
  - conda-forge
dependencies:
  - python=3.10
  - conda-forge::cookiecutter
  - ca-certificates
  - openssl
  - conda-forge::huggingface_hub
  - certifi
  - jupyterlab
  - transformers
  - pytorch==2.2.2
  - pytorch-cuda=11.8
  - conda-forge::requests=2.27.1
  - conda-forge::datasets==2.16.1
  - conda-forge::cudatoolkit
  - conda-forge::tensorboard
  - conda-forge::peft
  - wandb
