name: base
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - archspec=0.2.2
  - blas=2.16
  - boltons=23.0.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.21.0
  - ca-certificates=2023.7.22
  - certifi=2023.7.22
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - conda=23.10.0
  - conda-content-trust=0.2.0
  - conda-libmamba-solver=23.11.0
  - conda-package-handling=2.2.0
  - conda-package-streaming=0.9.0
  - cryptography=41.0.5
  - filelock=3.13.1
  - fmt=10.1.1
  - icu=73.2
  - idna=3.4
  - intel-openmp=2023.1.0
  - jinja2=3.1.2
  - jsonpatch=1.33
  - jsonpointer=2.4
  - keyutils=1.6.1
  - krb5=1.20.1
  - ld_impl_linux-64=2.40
  - libarchive=3.7.2
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=8.4.0
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=13.2.0
  - libiconv=1.17
  - liblapack=3.8.0
  - liblapacke=3.8.0
  - libmamba=1.5.3
  - libmambapy=1.5.3
  - libnghttp2=1.57.0
  - libsolv=0.7.24
  - libssh2=1.10.0
  - libstdcxx-ng=13.2.0
  - libuuid=1.41.5
  - libxml2=2.11.5
  - libzlib=1.2.13
  - llvm-openmp=15.0.7
  - lz4-c=1.9.4
  - lzo=2.10
  - mamba=1.5.3
  - markupsafe=2.1.3
  - mkl=2020.2
  - mpmath=1.3.0
  - ncurses=6.4
  - networkx=3.2.1
  - openssl=3.1.4
  - packaging=23.2
  - pcre2=10.42
  - pip=23.3.1
  - pluggy=1.3.0
  - pybind11-abi=4
  - pycosat=0.6.6
  - pycparser=2.21
  - pysocks=1.7.1
  - python=3.11.5
  - python_abi=3.11
  - pytorch=2.1.0
  - pytorch-mutex=1.0
  - pyyaml=6.0.1
  - readline=8.2
  - reproc=14.2.4.post0
  - reproc-cpp=14.2.4.post0
  - requests=2.31.0
  - ruamel.yaml=0.18.5
  - ruamel.yaml.clib=0.2.7
  - setuptools=68.2.2
  - sqlite=3.41.2
  - sympy=1.12
  - tk=8.6.12
  - tqdm=4.66.1
  - truststore=0.8.0
  - typing_extensions=4.8.0
  - tzdata=2023c
  - urllib3=2.0.7
  - wheel=0.41.3
  - xz=5.4.2
  - yaml=0.2.5
  - yaml-cpp=0.8.0
  - zlib=1.2.13
  - zstandard=0.22.0
  - zstd=1.5.5
  - pip:
      - accelerate==0.24.1
      - fsspec==2023.10.0
      - huggingface-hub==0.18.0
      - marshmallow==3.20.2
      - marshmallow-dataclass==8.6.0
      - mypy-extensions==1.0.0
      - numpy==1.26.1
      - psutil==5.9.6
      - typing-inspect==0.9.0
