name: rugpt_dev
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=2.1.0
  - accelerate=0.27.0
  - aiohttp=3.9.3
  - aiosignal=1.3.1
  - anyio=4.2.0
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=2.4.1
  - async-timeout=4.0.3
  - attrs=23.2.0
  - aws-c-auth=0.7.15
  - aws-c-cal=0.6.9
  - aws-c-common=0.9.12
  - aws-c-compression=0.2.17
  - aws-c-event-stream=0.4.1
  - aws-c-http=0.8.0
  - aws-c-io=0.14.3
  - aws-c-mqtt=0.10.1
  - aws-c-s3=0.5.0
  - aws-c-sdkutils=0.1.14
  - aws-checksums=0.1.17
  - aws-crt-cpp=0.26.1
  - aws-sdk-cpp=1.11.242
  - babel=2.14.0
  - beautifulsoup4=4.12.3
  - binaryornot=0.4.4
  - bitsandbytes=0.42.0
  - blas=1.0
  - bleach=6.1.0
  - blinker=1.7.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.26.0
  - ca-certificates=2024.2.2
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.3.2
  - certifi=2024.2.2
  - cffi=1.16.0
  - chardet=4.0.0
  - charset-normalizer=2.0.12
  - click=8.1.7
  - colorama=0.4.6
  - comm=0.2.1
  - cookiecutter=2.5.0
  - cryptography=42.0.3
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cudatoolkit=11.8.0
  - datasets=2.16.1
  - debugpy=1.8.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dill=0.3.7
  - entrypoints=0.4
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - ffmpeg=4.3
  - filelock=3.13.1
  - fqdn=1.5.1
  - freetype=2.12.1
  - frozenlist=1.4.1
  - fsspec=2023.10.0
  - gflags=2.2.2
  - glog=0.6.0
  - gmp=6.3.0
  - gmpy2=2.1.2
  - gnutls=3.6.13
  - google-auth=2.28.0
  - google-auth-oauthlib=1.2.0
  - grpcio=1.60.1
  - huggingface_hub=0.20.2
  - icu=73.2
  - idna=3.6
  - importlib-metadata=7.0.1
  - importlib_resources=6.1.1
  - intel-openmp=2022.1.0
  - ipykernel=6.29.2
  - ipython=8.18.1
  - ipython_genutils=0.2.0
  - isoduration=20.11.0
  - jedi=0.19.1
  - jinja2=3.1.3
  - jpeg=9e
  - json5=0.9.14
  - jsonpointer=2.4
  - jsonschema=4.21.1
  - jsonschema-specifications=2023.12.1
  - jsonschema-with-format-nongpl=4.21.1
  - jupyter_client=7.4.9
  - jupyter_core=5.7.1
  - jupyter_events=0.9.0
  - jupyter_server=2.12.5
  - jupyter_server_terminals=0.5.2
  - jupyterlab=3.5.3
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.16.6
  - keyutils=1.6.1
  - krb5=1.21.2
  - lame=3.100
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20230802.1
  - libarrow=15.0.0
  - libarrow-acero=15.0.0
  - libarrow-dataset=15.0.0
  - libarrow-flight=15.0.0
  - libarrow-flight-sql=15.0.0
  - libarrow-gandiva=15.0.0
  - libarrow-substrait=15.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.8.1.2
  - libcurand=10.3.4.107
  - libcurl=8.5.0
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgomp=13.2.0
  - libgoogle-cloud=2.12.0
  - libgrpc=1.60.1
  - libiconv=1.17
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - libllvm15=15.0.7
  - libnghttp2=1.58.0
  - libnl=3.9.0
  - libnpp=11.8.0.86
  - libnsl=2.0.1
  - libnuma=2.0.16
  - libnvjpeg=11.9.0.86
  - libparquet=15.0.0
  - libpng=1.6.42
  - libprotobuf=4.25.1
  - libre2-11=2023.06.02
  - libsodium=1.0.18
  - libsqlite=3.45.1
  - libssh2=1.11.0
  - libstdcxx-ng=13.2.0
  - libthrift=0.19.0
  - libtiff=4.5.0
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libwebp-base=1.3.2
  - libxcb=1.13
  - libxcrypt=4.4.36
  - libxml2=2.12.5
  - libzlib=1.2.13
  - llvm-openmp=15.0.7
  - lz4-c=1.9.4
  - markdown=3.5.2
  - markdown-it-py=3.0.0
  - markupsafe=2.1.5
  - matplotlib-inline=0.1.6
  - mdurl=0.1.2
  - mistune=3.0.2
  - mkl=2022.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multidict=6.0.5
  - multiprocess=0.70.15
  - nbclassic=1.0.0
  - nbclient=0.8.0
  - nbconvert=7.16.0
  - nbconvert-core=7.16.0
  - nbconvert-pandoc=7.16.0
  - nbformat=5.9.2
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - nettle=3.6
  - networkx=3.2.1
  - notebook=6.5.6
  - notebook-shim=0.2.4
  - numpy=1.26.4
  - oauthlib=3.2.2
  - openh264=2.1.1
  - openjpeg=2.5.0
  - openssl=3.2.1
  - orc=1.9.2
  - overrides=7.7.0
  - packaging=23.2
  - pandas=2.2.0
  - pandoc=3.1.12
  - pandocfilters=1.5.0
  - parso=0.8.3
  - peft=0.8.2
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=24.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.2.0
  - prometheus_client=0.20.0
  - prompt-toolkit=3.0.42
  - protobuf=4.25.1
  - psutil=5.9.8
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyarrow=15.0.0
  - pyarrow-hotfix=0.6
  - pyasn1=0.5.1
  - pyasn1-modules=0.3.0
  - pycparser=2.21
  - pygments=2.17.2
  - pyjwt=2.8.0
  - pyopenssl=24.0.0
  - pysocks=1.7.1
  - python=3.9.18
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.19.1
  - python-json-logger=2.0.7
  - python-slugify=8.0.4
  - python-tzdata=2024.1
  - python-xxhash=3.4.1
  - python_abi=3.9
  - pytorch=2.2.0
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pyu2f=0.1.5
  - pyyaml=6.0.1
  - pyzmq=24.0.1
  - rdma-core=50.0
  - re2=2023.06.02
  - readline=8.2
  - referencing=0.33.0
  - regex=2023.12.25
  - requests=2.27.1
  - requests-oauthlib=1.3.1
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.7.0
  - rpds-py=0.18.0
  - rsa=4.9
  - s2n=1.4.3
  - safetensors=0.4.2
  - scipy=1.12.0
  - send2trash=1.8.2
  - setuptools=69.0.3
  - six=1.16.0
  - snappy=1.1.10
  - sniffio=1.3.0
  - soupsieve=2.5
  - stack_data=0.6.2
  - sympy=1.12
  - tensorboard=2.15.2
  - tensorboard-data-server=0.7.0
  - terminado=0.18.0
  - text-unidecode=1.3
  - tinycss2=1.2.1
  - tk=8.6.13
  - tokenizers=0.15.2
  - tomli=2.0.1
  - torchaudio=2.2.0
  - torchtriton=2.2.0
  - torchvision=0.17.0
  - tornado=6.3.3
  - tqdm=4.66.2
  - traitlets=5.14.1
  - transformers=4.37.2
  - types-python-dateutil=2.8.19.20240106
  - typing-extensions=4.9.0
  - typing_extensions=4.9.0
  - typing_utils=0.1.0
  - tzdata=2024a
  - ucx=1.15.0
  - uri-template=1.3.0
  - urllib3=1.26.18
  - wcwidth=0.2.13
  - webcolors=1.13
  - webencodings=0.5.1
  - websocket-client=1.7.0
  - werkzeug=3.0.1
  - wheel=0.42.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xxhash=0.8.2
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.9.4
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - marshmallow==3.20.2
      - marshmallow-dataclass==8.6.0
      - mypy-extensions==1.0.0
      - typing-inspect==0.9.0
