name: rugpt_low_resource
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=2.1.0
  - accelerate=0.29.2
  - aiohttp=3.9.3
  - aiosignal=1.3.1
  - anyio=4.3.0
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=2.4.1
  - async-lru=2.0.4
  - async-timeout=4.0.3
  - attrs=23.2.0
  - aws-c-auth=0.7.16
  - aws-c-cal=0.6.10
  - aws-c-common=0.9.13
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.1
  - aws-c-io=0.14.5
  - aws-c-mqtt=0.10.2
  - aws-c-s3=0.5.2
  - aws-c-sdkutils=0.1.15
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.26.2
  - aws-sdk-cpp=1.11.267
  - babel=2.14.0
  - beautifulsoup4=4.12.3
  - binaryornot=0.4.4
  - bleach=6.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.28.1
  - ca-certificates=2024.2.2
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2024.2.2
  - cffi=1.16.0
  - chardet=5.2.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - colorama=0.4.6
  - comm=0.2.2
  - cookiecutter=2.6.0
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cuda-version=11.8
  - cudatoolkit=11.8.0
  - cudnn=8.9.7.29
  - datasets=2.19.0
  - debugpy=1.8.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dill=0.3.8
  - entrypoints=0.4
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - filelock=3.13.4
  - fqdn=1.5.1
  - freetype=2.12.1
  - frozenlist=1.4.1
  - fsspec=2024.3.1
  - gflags=2.2.2
  - glog=0.7.0
  - gmp=6.3.0
  - gmpy2=2.1.5
  - grpcio=1.60.1
  - h11=0.14.0
  - h2=4.1.0
  - hpack=4.0.0
  - httpcore=1.0.5
  - httpx=0.27.0
  - huggingface_hub=0.22.2
  - hyperframe=6.0.1
  - icu=73.2
  - idna=3.7
  - importlib-metadata=7.1.0
  - importlib_metadata=7.1.0
  - importlib_resources=6.4.0
  - ipykernel=6.29.3
  - ipython=8.22.2
  - ipython_genutils=0.2.0
  - isoduration=20.11.0
  - jedi=0.19.1
  - jinja2=3.1.3
  - json5=0.9.25
  - jsonpointer=2.4
  - jsonschema=4.21.1
  - jsonschema-specifications=2023.12.1
  - jsonschema-with-format-nongpl=4.21.1
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.1
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.1.6
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.1
  - keyutils=1.6.1
  - krb5=1.21.2
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20230802.1
  - libarrow=15.0.0
  - libarrow-acero=15.0.0
  - libarrow-dataset=15.0.0
  - libarrow-flight=15.0.0
  - libarrow-flight-sql=15.0.0
  - libarrow-gandiva=15.0.0
  - libarrow-substrait=15.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.9.1.3
  - libcurand=10.3.5.147
  - libcurl=8.7.1
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.20
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgoogle-cloud=2.17.0
  - libgoogle-cloud-storage=2.17.0
  - libgrpc=1.60.1
  - libhwloc=2.10.0
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libllvm16=16.0.6
  - libmagma=2.7.2
  - libmagma_sparse=2.7.2
  - libnghttp2=1.58.0
  - libnl=3.9.0
  - libnpp=11.8.0.86
  - libnsl=2.0.1
  - libnvjpeg=11.9.0.86
  - libopenblas=0.3.27
  - libparquet=15.0.0
  - libpng=1.6.43
  - libprotobuf=4.25.1
  - libre2-11=2023.09.01
  - libsodium=1.0.18
  - libsqlite=3.45.3
  - libssh2=1.11.0
  - libstdcxx-ng=13.2.0
  - libthrift=0.19.0
  - libtiff=4.6.0
  - libtorch=2.1.2
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libuv=1.48.0
  - libwebp-base=1.4.0
  - libxcb=1.15
  - libxcrypt=4.4.36
  - libxml2=2.12.6
  - libzlib=1.2.13
  - llvm-openmp=18.1.3
  - lz4-c=1.9.4
  - magma=2.7.2
  - markdown=3.6
  - markdown-it-py=3.0.0
  - markupsafe=2.1.5
  - matplotlib-inline=0.1.7
  - mdurl=0.1.2
  - mistune=3.0.2
  - mkl=2023.2.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multidict=6.0.5
  - multiprocess=0.70.16
  - nbclassic=1.0.0
  - nbclient=0.10.0
  - nbconvert=7.16.3
  - nbconvert-core=7.16.3
  - nbconvert-pandoc=7.16.3
  - nbformat=5.10.4
  - nccl=2.21.5.1
  - ncurses=6.4.20240210
  - nest-asyncio=1.6.0
  - networkx=3.3
  - notebook=7.1.3
  - notebook-shim=0.2.4
  - numpy=1.26.4
  - openjpeg=2.5.2
  - openssl=3.2.1
  - orc=1.9.2
  - overrides=7.7.0
  - packaging=24.0
  - pandas=2.2.2
  - pandoc=3.1.13
  - pandocfilters=1.5.0
  - parso=0.8.4
  - peft=0.10.0
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.3.0
  - pip=24.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.2.1
  - prometheus_client=0.20.0
  - prompt-toolkit=3.0.42
  - protobuf=4.25.1
  - psutil=5.9.8
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyarrow=15.0.0
  - pyarrow-hotfix=0.6
  - pycparser=2.22
  - pygments=2.17.2
  - pysocks=1.7.1
  - python=3.10.14
  - python-dateutil=2.9.0
  - python-fastjsonschema=2.19.1
  - python-json-logger=2.0.7
  - python-slugify=8.0.4
  - python-tzdata=2024.1
  - python-xxhash=3.4.1
  - python_abi=3.10
  - pytorch=2.1.2
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pyyaml=6.0.1
  - pyzmq=26.0.2
  - rdma-core=51.0
  - re2=2023.09.01
  - readline=8.2
  - referencing=0.34.0
  - regex=2024.4.16
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.7.1
  - rpds-py=0.18.0
  - s2n=1.4.5
  - safetensors=0.4.3
  - scipy=1.13.0
  - send2trash=1.8.3
  - setuptools=69.5.1
  - six=1.16.0
  - sleef=3.5.1
  - snappy=1.1.10
  - sniffio=1.3.1
  - soupsieve=2.5
  - stack_data=0.6.2
  - sympy=1.12
  - tbb=2021.12.0
  - tensorboard=2.16.2
  - tensorboard-data-server=0.7.0
  - terminado=0.18.1
  - text-unidecode=1.3
  - tinycss2=1.2.1
  - tk=8.6.13
  - tokenizers=0.15.2
  - tomli=2.0.1
  - torchaudio=2.1.2
  - torchvision=0.16.1
  - tornado=6.4
  - tqdm=4.66.2
  - traitlets=5.14.3
  - transformers=4.39.3
  - types-python-dateutil=2.9.0.20240316
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - typing_utils=0.1.0
  - tzdata=2024a
  - ucx=1.15.0
  - uri-template=1.3.0
  - urllib3=2.2.1
  - valgrind=3.22.0
  - wcwidth=0.2.13
  - webcolors=1.13
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - werkzeug=3.0.2
  - wheel=0.43.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xxhash=0.8.2
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.9.4
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - appdirs==1.4.4
      - bitsandbytes==0.43.1
      - docker-pycreds==0.4.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - marshmallow==3.21.1
      - marshmallow-dataclass==8.6.1
      - mypy-extensions==1.0.0
      - pip-review==1.3.0
      - sentry-sdk==1.45.0
      - setproctitle==1.3.3
      - smmap==5.0.1
      - torch-tb-profiler==0.4.3
      - typing-inspect==0.9.0
      - wandb==0.16.6
