checkpoint_base_cache_dir: /home/ybelova/repos/rugpt-memory/checkpoints/base/huggingface
checkpoint_dir: /media/public/ybelova/rugpt-memory/checkpoints
checkpoint_interval: 5
content_dir: '.'
eval_interval: 100
experiment_name: baseline:add_print:cos_sim:add_penalty:layers_1_1:adaptive_ent
log_dir: /home/ybelova/repos/rugpt-memory/logs/runs/pretrain_agent/ones
max_checkpoints: 5
max_eval_steps: 32
pretrained_model_name_or_path: ai-forever/rugpt3small_based_on_gpt2
seed: 42   

base_model_params:
  load_in_4bit: false
  load_in_8bit: false
  add_lora: false

ltm_params:
  step_length: 32
  cnt_blocks_with_memory: 2
  device: cuda:1

memory_model_params:
  device: cuda:0
  d_mem: 16
  d_embd: 16
  num_vectors: 4
  n_dec_block: 1
  n_enc_block: 1

pretrain_params:
    episode_max_steps: 4
    iterations: 3000
    lr: 3e-5

rl_params:
  alpha_lr: 1e-4
  batches_per_update: 8
  batch_size: 32
  clip: 0.2
  clip_grad_norm: 1.0
  alpha_start: -6
  gamma: 0.99
  kl_target: 6.
  min_transitions_per_update: 256
  num_prefixes_for_reward_calc: 3
  target_entropy: 30.

trainer_args:
  batch_size: 32
  num_train_epochs: 1
  ltm_clip_grad_norm: 1.0
  ltm_learning_rate: 3e-5
  ltm_model_iterations: 1
  memory_model_learning_rate: 2e-5
  memory_model_iterations: 40
  optimizer: adamw   
  torch_dtype: float32




  
