checkpoint_base_cache_dir: /home/akarpov/jbelova/rugpt-memory/checkpoints/base/huggingface
checkpoint_dir: /home/akarpov/jbelova/rugpt-memory/checkpoints/train
checkpoint_interval: 50
content_dir: '.'
experiment_name: base
description: "Correct models. Correct reward logging. Correct dataset split. New dataset. No pretrain."
log_dir: /home/akarpov/jbelova/rugpt-memory/logs/runs/train
max_checkpoints: 1
max_eval_steps: 200
pretrained_model_name_or_path: ai-forever/rugpt3small_based_on_gpt2
seed: 42

base_model_params:
  load_in_4bit: false
  load_in_8bit: false
  add_lora: false

memory_model_params:
  device: cuda:0
  d_mem: 64
  d_embd: 768
  num_vectors: 10
  n_dec_block: 3
  n_enc_block: 2

trainer_args:
  batch_size: 16
  num_train_epochs: 1
  ltm_clip_grad_norm: 1.0
  ltm_learning_rate: 2e-5
  ltm_model_iterations: 15
  memory_model_learning_rate: 2e-5
  memory_model_iterations: 15
  optimizer: adamw   
  torch_dtype: float32

rl_params:
  alpha_lr: 1e-4
  alpha_start: -6
  batches_per_update: 6
  batch_size: 64
  clip: 0.2
  clip_grad_norm: 1.0
  gamma: 0.99
  kl_target: 3.
  min_transitions_per_update: 256
  num_prefixes_for_reward_calc: 3
  target_entropy: -10

ltm_params:
  cnt_blocks_with_memory: 2
  device: cuda:1
  step_length: 256
  
