experiment_name: increase_n_iterations
seed: 42
content_dir: '.'
pretrained_model_name_or_path: ai-forever/rugpt3small_based_on_gpt2
checkpoint_dir: /media/public/ybelova/rugpt-memory/checkpoints
checkpoint_base_cache_dir: /home/ybelova/repos/rugpt-memory/checkpoints/base/huggingface
checkpoint_interval: 5
max_eval_steps: 32
max_checkpoints: 5

base_model_params:
  load_in_4bit: false
  load_in_8bit: false
  add_lora: false

memory_model_params:
  device: cuda:0
  num_vectors: 8
  d_mem: 32
  n_enc_block: 1
  n_dec_block: 1


trainer_args:
  warmup_steps: 0
  gradient_accumulation_steps: 1
  torch_dtype: float32
  num_train_epochs: 1
  ltm_model_iterations: 50
  memory_model_iterations: 50
  batch_size: 4
  cut_by_shortest_article: True
  optimizer: adamw
  ltm_learning_rate: 3e-5
  memory_model_learning_rate: 3e-5
  step_length: 256

rl_params:
  num_prefixes_for_reward_calc: 3
  batches_per_update: 8
  batch_size: 4
  min_transitions_per_update: 64

ltm_params:
  device: cuda:1
  cnt_blocks_with_memory: 2
