experiment_name: first_experiment
seed: 42
content_dir: '.'
pretrained_model_name_or_path: ai-forever/ruGPT-3.5-13B
checkpoint_dir: /home/nikita_u/study/nir/repo/rugpt-memory/checkpoints
checkpoint_base_cache_dir: /home/nikita_u/study/nir/repo/rugpt-memory/checkpoints/base/huggingface
checkpoint_interval: 20
max_eval_steps: 32

base_model_params:
  load_in_4bit: true
  load_in_8bit: false
  add_lora: true

memory_model_params:
  device: cuda:0
  num_vectors: 8
  d_mem: 64
  n_enc_block: 1
  n_dec_block: 2


trainer_args:
  warmup_steps: 0
  gradient_accumulation_steps: 1
  fp16: True
  num_train_epochs: 1
  ltm_model_iterations: 10
  memory_model_iterations: 10
  batch_size: 4
  cut_by_shortest_article: True
  optimizer: adam
  ltm_learning_rate: 1e-5
  memory_model_learning_rate: 1e-5

rl_params:
  batches_per_update: 10
  batch_size: 4
  min_transitions_per_update: 16

ltm_params:
  device: cuda:1
  cnt_blocks_with_memory: 2
