checkpoint_base_cache_dir: /home/ybelova/repos/rugpt-memory/checkpoints/base/huggingface
checkpoint_dir: /media/public/ybelova/rugpt-memory/checkpoints
checkpoint_interval: 10
content_dir: '.'
experiment_name: base
log_dir: /home/ybelova/repos/rugpt-memory/logs/runs/train_new/
max_checkpoints: 5
max_eval_steps: 32
pretrained_model_name_or_path: ai-forever/rugpt3small_based_on_gpt2
seed: 42   

base_model_params:
  load_in_4bit: false
  load_in_8bit: false
  add_lora: false

memory_model_params:
  device: cuda:0
  d_mem: 64
  d_embd: 768
  num_vectors: 8
  n_dec_block: 2
  n_enc_block: 2

trainer_args:
  batch_size: 16
  num_train_epochs: 2
  ltm_clip_grad_norm: 1.0
  ltm_learning_rate: 5e-5
  ltm_model_iterations: 40
  memory_model_learning_rate: 5e-5
  memory_model_iterations: 40
  optimizer: adamw   
  torch_dtype: float32

rl_params:
  alpha_lr: 1e-4
  alpha_start: -6
  batches_per_update: 10
  batch_size: 16
  clip: 0.2
  clip_grad_norm: 1.0
  gamma: 0.99
  kl_target: 1.5
  min_transitions_per_update: 128
  num_prefixes_for_reward_calc: 3
  target_entropy: 48

ltm_params:
  cnt_blocks_with_memory: 2
  device: cuda:1
  step_length: 256
  
